[2024-09-05T12:26:12.043+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:12.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:26:12.057+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:26:12.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:12.117+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:26:12.111+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:26:12.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:12.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.121 seconds
[2024-09-05T12:26:54.007+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:54.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:26:54.011+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:26:54.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:54.062+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:26:54.054+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:26:54.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:26:54.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.096 seconds
[2024-09-05T12:27:25.035+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:25.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:27:25.038+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:27:25.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:25.058+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:27:25.054+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:27:25.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:25.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-09-05T12:27:55.397+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:55.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:27:55.400+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:27:55.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:55.420+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:27:55.416+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:27:55.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:27:55.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.065 seconds
[2024-09-05T12:28:25.995+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:25.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:28:25.997+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:28:25.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:26.015+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:28:26.011+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:28:26.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:26.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-09-05T12:28:56.308+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:56.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:28:56.310+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:28:56.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:56.328+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:28:56.325+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:28:56.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:28:56.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-09-05T12:29:26.536+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:26.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:29:26.540+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:29:26.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:26.578+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:29:26.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:29:26.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:26.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.107 seconds
[2024-09-05T12:29:57.358+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:57.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:29:57.360+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:29:57.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:57.379+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:29:57.375+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:29:57.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:29:57.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2024-09-05T12:30:27.583+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:27.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:30:27.585+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:30:27.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:27.609+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:30:27.604+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:30:27.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:27.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2024-09-05T12:30:57.710+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:57.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:30:57.712+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:30:57.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:57.736+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:30:57.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import extract_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:30:57.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:30:57.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-09-05T12:45:14.074+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:14.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:45:14.077+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:45:14.077+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:14.184+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:45:14.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:45:14.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:14.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.193 seconds
[2024-09-05T12:45:44.707+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:44.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:45:44.710+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:45:44.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:44.728+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:45:44.724+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:45:44.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:45:44.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-09-05T12:46:14.842+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:14.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:46:14.845+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:46:14.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:14.859+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:46:14.856+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:46:14.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:14.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-09-05T12:46:45.465+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:45.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:46:45.467+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:46:45.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:45.481+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:46:45.478+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:46:45.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:46:45.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-09-05T12:47:15.899+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:15.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:47:15.901+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:47:15.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:15.915+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:47:15.913+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:47:15.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:15.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T12:47:46.134+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:46.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:47:46.136+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:47:46.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:46.149+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:47:46.146+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:47:46.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:47:46.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T12:48:16.344+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:16.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:48:16.346+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:48:16.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:16.360+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:48:16.358+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:48:16.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:16.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-09-05T12:48:46.578+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:46.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:48:46.580+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:48:46.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:46.594+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:48:46.592+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:48:46.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:48:46.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T12:49:16.757+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:16.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:49:16.759+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:49:16.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:16.779+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:49:16.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:49:16.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:16.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-09-05T12:49:47.015+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:47.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:49:47.017+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:49:47.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:47.030+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:49:47.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:49:47.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:49:47.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-09-05T12:50:17.386+0000] {processor.py:161} INFO - Started process (PID=605) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:17.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:50:17.388+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:50:17.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:17.406+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:50:17.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:50:17.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:17.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-09-05T12:50:47.784+0000] {processor.py:161} INFO - Started process (PID=663) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:47.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:50:47.786+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:50:47.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:47.801+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:50:47.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:50:47.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:50:47.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-09-05T12:51:18.242+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:18.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:51:18.244+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:51:18.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:18.258+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:51:18.255+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:51:18.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:18.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-09-05T12:51:48.651+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:48.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:51:48.653+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:51:48.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:48.666+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:51:48.664+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:51:48.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:51:48.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-09-05T12:52:19.052+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:19.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:52:19.054+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:52:19.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:19.068+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:52:19.065+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:52:19.069+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:19.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-09-05T12:52:49.176+0000] {processor.py:161} INFO - Started process (PID=890) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:49.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:52:49.178+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:52:49.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:49.192+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:52:49.189+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:52:49.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:52:49.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-09-05T12:53:19.387+0000] {processor.py:161} INFO - Started process (PID=947) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:19.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:53:19.389+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:53:19.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:19.403+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:53:19.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:53:19.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:19.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-09-05T12:53:49.551+0000] {processor.py:161} INFO - Started process (PID=1004) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:49.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:53:49.553+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:53:49.552+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:49.572+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:53:49.568+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:53:49.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:53:49.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-09-05T12:54:19.745+0000] {processor.py:161} INFO - Started process (PID=1061) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:19.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:54:19.749+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:54:19.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:19.767+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:54:19.763+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:54:19.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:19.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-09-05T12:54:50.389+0000] {processor.py:161} INFO - Started process (PID=1118) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:50.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:54:50.390+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:54:50.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:50.404+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:54:50.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:54:50.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:54:50.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T12:55:20.466+0000] {processor.py:161} INFO - Started process (PID=1175) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:20.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:55:20.468+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:55:20.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:20.483+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:55:20.480+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:55:20.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:20.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-09-05T12:55:50.630+0000] {processor.py:161} INFO - Started process (PID=1232) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:50.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:55:50.633+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:55:50.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:50.645+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:55:50.643+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:55:50.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:55:50.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T12:56:20.796+0000] {processor.py:161} INFO - Started process (PID=1289) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:20.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:56:20.797+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:56:20.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:20.813+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:56:20.810+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:56:20.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:20.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-09-05T12:56:50.998+0000] {processor.py:161} INFO - Started process (PID=1346) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:50.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:56:51.000+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:56:50.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:51.014+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:56:51.011+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:56:51.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:56:51.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T12:57:21.196+0000] {processor.py:161} INFO - Started process (PID=1401) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:21.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:57:21.198+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:57:21.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:21.216+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:57:21.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:57:21.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:21.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-09-05T12:57:51.412+0000] {processor.py:161} INFO - Started process (PID=1458) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:51.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:57:51.413+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:57:51.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:51.432+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:57:51.429+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:57:51.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:57:51.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-09-05T12:58:21.986+0000] {processor.py:161} INFO - Started process (PID=1515) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:21.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:58:21.988+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:58:21.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:22.002+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:58:21.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:58:22.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:22.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T12:58:52.315+0000] {processor.py:161} INFO - Started process (PID=1572) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:52.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:58:52.316+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:58:52.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:52.330+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:58:52.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:58:52.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:58:52.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-09-05T12:59:22.783+0000] {processor.py:161} INFO - Started process (PID=1629) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:22.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:59:22.785+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:59:22.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:22.797+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:59:22.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:59:22.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:22.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-09-05T12:59:53.072+0000] {processor.py:161} INFO - Started process (PID=1686) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:53.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T12:59:53.074+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:59:53.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:53.087+0000] {logging_mixin.py:188} INFO - [2024-09-05T12:59:53.084+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T12:59:53.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T12:59:53.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T13:00:23.488+0000] {processor.py:161} INFO - Started process (PID=1743) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:23.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:00:23.489+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:00:23.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:23.503+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:00:23.500+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:00:23.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:23.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T13:00:53.686+0000] {processor.py:161} INFO - Started process (PID=1800) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:53.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:00:53.687+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:00:53.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:53.701+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:00:53.698+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:00:53.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:00:53.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-09-05T13:01:23.910+0000] {processor.py:161} INFO - Started process (PID=1857) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:23.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:01:23.911+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:01:23.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:23.925+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:01:23.922+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:01:23.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:23.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T13:01:54.203+0000] {processor.py:161} INFO - Started process (PID=1913) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:54.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:01:54.205+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:01:54.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:54.218+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:01:54.215+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:01:54.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:01:54.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-09-05T13:02:24.606+0000] {processor.py:161} INFO - Started process (PID=1970) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:24.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:02:24.608+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:02:24.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:24.622+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:02:24.619+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:02:24.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:24.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-09-05T13:02:54.673+0000] {processor.py:161} INFO - Started process (PID=2027) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:54.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:02:54.675+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:02:54.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:54.688+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:02:54.685+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:02:54.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:02:54.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-09-05T13:03:25.017+0000] {processor.py:161} INFO - Started process (PID=2084) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:25.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:03:25.018+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:03:25.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:25.032+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:03:25.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:03:25.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:25.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-09-05T13:03:55.102+0000] {processor.py:161} INFO - Started process (PID=2141) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:55.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:03:55.104+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:03:55.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:55.117+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:03:55.114+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:03:55.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:03:55.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-09-05T13:04:25.396+0000] {processor.py:161} INFO - Started process (PID=2197) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:25.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:04:25.398+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:25.397+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:25.416+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:25.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:04:25.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:25.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-09-05T13:04:30.588+0000] {processor.py:161} INFO - Started process (PID=2217) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:30.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:04:30.591+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:30.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:30.628+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:30.622+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:04:30.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:30.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2024-09-05T13:04:32.009+0000] {processor.py:161} INFO - Started process (PID=2223) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:32.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:04:32.011+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:32.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:32.038+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:32.035+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:04:32.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:32.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-09-05T13:04:37.971+0000] {processor.py:161} INFO - Started process (PID=2245) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:37.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:04:37.972+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:37.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:37.999+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:04:37.997+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:04:38.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:04:38.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2024-09-05T13:06:18.173+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:18.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:06:18.178+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:06:18.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:18.231+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:06:18.226+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:06:18.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:18.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.143 seconds
[2024-09-05T13:06:48.611+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:48.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:06:48.613+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:06:48.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:48.632+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:06:48.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:06:48.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:06:48.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-09-05T13:07:19.195+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:19.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:07:19.197+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:07:19.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:19.214+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:07:19.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:07:19.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:19.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-09-05T13:07:49.862+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:49.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:07:49.864+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:07:49.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:49.880+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:07:49.878+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:07:49.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:07:49.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-09-05T13:08:20.048+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:20.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:08:20.050+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:08:20.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:20.069+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:08:20.065+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:08:20.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:20.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-09-05T13:08:50.398+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:50.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:08:50.401+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:08:50.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:50.435+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:08:50.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:08:50.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:08:50.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2024-09-05T13:09:18.344+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:18.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:18.346+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:18.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:18.373+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:18.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from src.pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'src'
[2024-09-05T13:09:18.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:18.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-09-05T13:09:21.387+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:21.389+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:21.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.420+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:21.417+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from src.pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'src'
[2024-09-05T13:09:21.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.074 seconds
[2024-09-05T13:09:21.802+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:21.804+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:21.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.836+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:21.832+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from src.pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'src'
[2024-09-05T13:09:21.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:21.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2024-09-05T13:09:52.321+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:52.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:52.323+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:52.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:52.340+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:52.337+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from src.pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'src'
[2024-09-05T13:09:52.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:52.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-09-05T13:09:54.566+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:54.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:54.570+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:54.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:54.607+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:54.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from src.pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'src'
[2024-09-05T13:09:54.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:54.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.076 seconds
[2024-09-05T13:09:58.692+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:58.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:09:58.694+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:58.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:58.722+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:09:58.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:09:58.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:09:58.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-09-05T13:10:28.898+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:28.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:10:28.900+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:10:28.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:28.913+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:10:28.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:10:28.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:28.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-09-05T13:10:59.918+0000] {processor.py:161} INFO - Started process (PID=600) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:59.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:10:59.920+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:10:59.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:59.937+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:10:59.933+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:10:59.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:10:59.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-09-05T13:11:30.053+0000] {processor.py:161} INFO - Started process (PID=657) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:30.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:11:30.054+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:30.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:30.071+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:30.069+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:11:30.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:30.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-09-05T13:11:51.644+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:51.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:11:51.646+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:51.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:51.670+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:51.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:11:51.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:51.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-09-05T13:11:57.546+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:57.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:11:57.549+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:57.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:57.570+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:11:57.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:11:57.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:11:57.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-09-05T13:12:27.651+0000] {processor.py:161} INFO - Started process (PID=750) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:27.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:12:27.652+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:12:27.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:27.671+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:12:27.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:12:27.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:27.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-09-05T13:12:57.934+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:57.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:12:57.936+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:12:57.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:57.950+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:12:57.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:12:57.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:12:57.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-09-05T13:13:28.072+0000] {processor.py:161} INFO - Started process (PID=856) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:28.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:13:28.074+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:13:28.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:28.091+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:13:28.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:13:28.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:28.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-09-05T13:13:58.629+0000] {processor.py:161} INFO - Started process (PID=913) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:58.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:13:58.631+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:13:58.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:58.646+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:13:58.643+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:13:58.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:13:58.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-09-05T13:14:29.264+0000] {processor.py:161} INFO - Started process (PID=970) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:29.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:14:29.266+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:14:29.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:29.281+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:14:29.277+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:14:29.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:29.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T13:14:59.765+0000] {processor.py:161} INFO - Started process (PID=1028) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:59.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:14:59.769+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:14:59.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:59.785+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:14:59.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:14:59.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:14:59.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-09-05T13:15:30.113+0000] {processor.py:161} INFO - Started process (PID=1085) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:30.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:15:30.115+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:30.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:30.132+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:30.128+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:15:30.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:30.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-09-05T13:15:35.580+0000] {processor.py:161} INFO - Started process (PID=1116) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:35.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:15:35.582+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:35.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:35.610+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:35.608+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from data_ingestion import ingest_data
ModuleNotFoundError: No module named 'data_ingestion'
[2024-09-05T13:15:35.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:35.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2024-09-05T13:15:40.657+0000] {processor.py:161} INFO - Started process (PID=1123) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:40.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:15:40.660+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:40.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:40.690+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:40.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from data_ingestion import ingest_data
ModuleNotFoundError: No module named 'data_ingestion'
[2024-09-05T13:15:40.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:40.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-09-05T13:15:57.256+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:57.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:15:57.257+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:57.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:57.284+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:15:57.280+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:15:57.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:15:57.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-09-05T13:16:00.662+0000] {processor.py:161} INFO - Started process (PID=1148) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:00.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:16:00.664+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:00.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:00.699+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:00.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:16:00.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:00.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.074 seconds
[2024-09-05T13:16:02.874+0000] {processor.py:161} INFO - Started process (PID=1162) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:02.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:16:02.878+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:02.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:02.908+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:02.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:16:02.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:02.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2024-09-05T13:16:04.916+0000] {processor.py:161} INFO - Started process (PID=1177) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:04.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:16:04.918+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:04.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:04.942+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:04.939+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:16:04.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:04.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-09-05T13:16:35.915+0000] {processor.py:161} INFO - Started process (PID=1240) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:35.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:16:35.916+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:35.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:35.931+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:16:35.927+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:16:35.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:16:35.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-09-05T13:17:06.576+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:06.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:17:06.577+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:17:06.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:06.594+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:17:06.591+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:17:06.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:06.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-09-05T13:17:37.243+0000] {processor.py:161} INFO - Started process (PID=1354) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:37.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:17:37.245+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:17:37.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:37.260+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:17:37.257+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:17:37.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:17:37.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-09-05T13:18:07.881+0000] {processor.py:161} INFO - Started process (PID=1411) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:07.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:18:07.882+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:18:07.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:07.897+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:18:07.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:18:07.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:07.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-09-05T13:18:38.077+0000] {processor.py:161} INFO - Started process (PID=1468) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:38.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:18:38.078+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:18:38.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:38.091+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:18:38.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:18:38.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:18:38.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-09-05T13:19:12.621+0000] {processor.py:161} INFO - Started process (PID=1525) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:12.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:19:12.643+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:19:12.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:12.776+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:19:12.767+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:19:12.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:12.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.234 seconds
[2024-09-05T13:19:43.659+0000] {processor.py:161} INFO - Started process (PID=1582) to work on /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:43.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-05T13:19:43.662+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:19:43.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:43.680+0000] {logging_mixin.py:188} INFO - [2024-09-05T13:19:43.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-05T13:19:43.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-05T13:19:43.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
