[2024-09-08T13:22:38.659+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:22:38.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:22:38.663+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:22:38.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:22:38.710+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:22:38.702+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:22:38.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:22:38.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.120 seconds
[2024-09-08T13:23:09.321+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:09.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:23:09.324+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:23:09.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:09.360+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:23:09.352+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:23:09.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:09.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.084 seconds
[2024-09-08T13:23:39.532+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:39.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:23:39.534+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:23:39.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:39.552+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:23:39.548+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:23:39.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:23:39.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-09-08T13:24:09.763+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:09.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:24:09.767+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:24:09.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:09.793+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:24:09.787+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:24:09.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:09.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-09-08T13:24:40.276+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:40.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:24:40.278+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:24:40.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:40.301+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:24:40.297+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:24:40.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:24:40.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-09-08T13:25:10.982+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:10.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:25:10.988+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:25:10.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:11.021+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:25:11.014+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:25:11.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:11.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.128 seconds
[2024-09-08T13:25:41.501+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:41.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:25:41.503+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:25:41.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:41.532+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:25:41.527+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:25:41.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:25:41.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.080 seconds
[2024-09-08T13:26:11.895+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:11.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:26:11.898+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:26:11.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:11.923+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:26:11.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:26:11.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:11.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-09-08T13:26:42.210+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:42.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:26:42.212+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:26:42.212+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:42.234+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:26:42.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:26:42.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:26:42.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-09-08T13:27:12.836+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:12.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:27:12.838+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:27:12.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:12.867+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:27:12.860+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:27:12.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:12.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2024-09-08T13:27:43.039+0000] {processor.py:161} INFO - Started process (PID=604) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:43.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:27:43.042+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:27:43.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:43.076+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:27:43.069+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:27:43.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:27:43.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2024-09-08T13:28:13.533+0000] {processor.py:161} INFO - Started process (PID=661) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:13.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:28:13.539+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:28:13.538+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:13.573+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:28:13.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:28:13.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:13.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.121 seconds
[2024-09-08T13:28:44.459+0000] {processor.py:161} INFO - Started process (PID=718) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:44.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:28:44.464+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:28:44.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:44.499+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:28:44.491+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:28:44.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:28:44.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.107 seconds
[2024-09-08T13:29:15.216+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:15.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:29:15.219+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:29:15.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:15.252+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:29:15.247+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:29:15.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:15.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.089 seconds
[2024-09-08T13:29:45.407+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:45.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-09-08T13:29:45.411+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:29:45.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:45.440+0000] {logging_mixin.py:188} INFO - [2024-09-08T13:29:45.434+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 6, in <module>
    from pipeline.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'pipeline'
[2024-09-08T13:29:45.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-09-08T13:29:45.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.079 seconds
